/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Models: typeof import('./../../components/01.kit/UModalWrapper/models/index.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAppPanel: typeof import('./../../components/01.kit/UAppPanel/index.ts')['default']
    UAvatar: typeof import('./../../components/01.kit/UAvatar/index.ts')['default']
    UChip: typeof import('./../../components/01.kit/UChip/index.ts')['default']
    UCluster: typeof import('./../../components/01.kit/UCluster/index.ts')['default']
    UDatePicker: typeof import('./../../components/01.kit/UDatePicker/index.ts')['default']
    UDrawer: typeof import('./../../components/01.kit/UDrawer/index.ts')['default']
    UExperienceRing: typeof import('./../../components/01.kit/UExperienceRing/index.ts')['default']
    UFlag: typeof import('./../../components/01.kit/UFlag/index.ts')['default']
    UGlassWrapper: typeof import('./../../components/01.kit/UGlassWrapper/index.ts')['default']
    UIcon: typeof import('./../../components/01.kit/UIcon/index.ts')['default']
    UInput: typeof import('./../../components/01.kit/UInput/index.ts')['default']
    UMarker: typeof import('./../../components/01.kit/UMarker/index.ts')['default']
    UModalWrapper: typeof import('./../../components/01.kit/UModalWrapper/index.ts')['default']
    UNotificationItem: typeof import('./../../components/01.kit/UNotificationItem/index.ts')['default']
    UPloader: typeof import('./../../components/01.kit/UPloader/index.ts')['default']
    UseInput: typeof import('./../../components/01.kit/UInput/models/useInput.ts')['default']
    USelect: typeof import('./../../components/01.kit/USelect/index.ts')['default']
    UTextArea: typeof import('./../../components/01.kit/UTextArea/index.ts')['default']
    UThemeSwitcher: typeof import('./../../components/01.kit/UThemeSwitcher/index.ts')['default']
    UTooltip: typeof import('./../../components/01.kit/UTooltip/index.ts')['default']
  }
}
